### ISSUE TITLE
Combine rain and rainRate tile to get rid of $current.rain

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#147]
**Describe the bug**
Current rain does not display though the Today's total on the card does update.

**To Reproduce**
Have a steady rainfall.

**Expected behavior**
Current rain should display.

**Screenshots**
2 screenshots during a thunderstorm. One from weewx-wdc one from Belchertown.

![Screenshot 2023-04-01 19 35 23](https://user-images.githubusercontent.com/12861605/229322903-f28bdefe-95fe-44d7-b549-5aa57d62e582.png)

![Screenshot 2023-04-01 19 36 17](https://user-images.githubusercontent.com/12861605/229322910-fcb7858f-d517-48e3-9cc0-ddfc58b85328.png)

**Comment by gary-hammer** [comment]
I think I know what is happening.
I do not have 'rain' as data. Davis uses rain_in for that.

I'm attaching MQTT data for both the Davis WiFi Logger and the Davis WeatherLinkLive
The system weewx-wdc is installed on uses the WLL.

So, if I want the displayed card to show 'Rain' and the proper value, what should be in the skin.conf?

[Davis-mqtt-info.txt](https://github.com/Daveiano/weewx-wdc/files/11132085/Davis-mqtt-info.txt)

**Comment by Daveiano** [comment]
> Current rain does not display though the Today's total on the card does update. 

You mean the big '0.00 in' right above the 'Todays Total', right? Yeah, I also noticed this, this will very rarely go above 0.00. I looked through some code to understand what's happening here. So the skin uses this to render the stat tiles on the front page:

For eg. the outTemp: `$current.outTemp`, or the outHumidity: `$current.outHumidity`. For the rain, its the same: `$current.rain`. BUT: What is `$current.rain`? I assume in WeeWX terms its the rain observed during the last archive interval (just guessing) - but this is misleading and not very useful. The season skins also does not show this and only shows  `$day.rain.sum` (the days total, see https://github.com/weewx/weewx/blob/master/skins/Seasons/current.inc#L32).

I would propose to remove the big '0.00 in' (`$current.rain`, since it does not make any useful sense) and instead combining the `rain` and `rainRate` tiles into one tile to show:
- Todays rain total
- current rain rate
- Days max rain rate

What do you think about this?

**Comment by gary-hammer** [comment]
I'd be happy with that, then I can just remove the rain rate tile.

**Comment by Daveiano** [comment]
Ok then, I will have a look as soon as I got time, will be included in the next release!

**Comment by gary-hammer** [comment]
Thanks.
Look forward to the fix.
