### ISSUE TITLE
weewx.conf "labels" are ignored

### ISSUE THREAD

**Issue by JDJoe** [Daveiano/weewx-wdc#162]
It seems that weewx.conf "labels" is ignored 
```

         [[[Labels]]]
            # Users frequently change the labels for these observation types
            [[[[Generic]]]]
                # inHumidity     = Inside Humidity
                # inTemp         = Inside Temperature
                extraTemp2     = New name 
```
extraTemp2 shows up as Temperature2

**Comment by Daveiano** [comment]
This is a snippet from weewx.conf, right? Could you provide the whole `[WdcReport]` section?

**Comment by JDJoe** [comment]
weewx conf is fine. It works with weewx skins. 
It seems that /lang/en.conf  is the one in charge of labels.

**Comment by Daveiano** [comment]
I assume you have configured a `lang` for `WdcReport` since your changes are not getting picked up by WeeWX. You need to make the changes directly to the `WDCReport` config in weewx.conf. But I can not say for sure without seeing any configs.

Read more about this in the wiki: https://github.com/Daveiano/weewx-wdc/wiki/WeeWX-related#changing-the-label-of-an-observation-for-the-whole-skin

**Comment by JDJoe** [comment]
```
    [[WdcReport]]
        skin = weewx-wdc
        enable = true
        lang = en
```

This is your default conf. So no, I did not add the lang.

**Comment by Daveiano** [comment]
Yes, I know this is the default, but I don't know what config you are using...

Anyway, it seems this is working now and there is also a dedicated wiki entry for that.
