### ISSUE TITLE
Forecast coordinates are ridiculously accurate

### ISSUE THREAD

**Issue by caphector** [Daveiano/weewx-wdc#191]
**Describe the bug**
I am using the OWM forecast; when the forecast is generated the page incudes GPS coordinates with 10+ decimal places of precision. These coordinates are too accurate to be useful; all that's needed is a general area and that can be done with four places coordinate precision like the page footer.

**Expected behavior**
~3-4 decimal places of precision

**Screenshots**
<img width="592" alt="Untitled" src="https://github.com/Daveiano/weewx-wdc/assets/8420750/29fbe76a-6a3a-4e9f-b0a5-d0d2ac60180c">

**Comment by Daveiano** [comment]
It seems that these are the exact coordinates provided to WeeWX in weewx.conf at `[Station] - latitude` and `[Station] - longitude`, at least that's the case for me.

I added a format of 4 decimal places in `skins/weewx-wdc/includes/forecast-table.inc`:

```diff
-    for $wloc
+    #set $wloc_list = $wloc.split(',')
+    #set $format_string = "{0:.3f}"
+    for $format_string.format($float($wloc_list[0])), $format_string.format($float($wloc_list[1]))
```

See https://github.com/Daveiano/weewx-wdc/commit/ad9dcbe7b7a963880063332b7a3dc48c0503a74b

Feel free to test the change by editing the template file! Otherwise, it will be included in the next release.

**Comment by caphector** [comment]
Thanks! I wasn't sure if the coords were from weewx.conf; I thought I had tested publishing after updating my weewx.conf, but I must have failed a step. 

In any case, I tried the code and it only prints three places which should look better under the Forecast table.

**Comment by Daveiano** [comment]
Yes, sorry I meant to write  "3 places"

**Comment by dave9997** [comment]
> It seems that these are the exact coordinates provided to WeeWX in weewx.conf at `[Station] - latitude` and `[Station] - longitude`, at least that's the case for me.
> 
> I added a format of 4 decimal places in `skins/weewx-wdc/includes/forecast-table.inc`:
> 
> ```diff
> -    for $wloc
> +    #set $wloc_list = $wloc.split(',')
> +    #set $format_string = "{0:.3f}"
> +    for $format_string.format($float($wloc_list[0])), $format_string.format($float($wloc_list[1]))
> ```
> 
> See [ad9dcbe](https://github.com/Daveiano/weewx-wdc/commit/ad9dcbe7b7a963880063332b7a3dc48c0503a74b)
> 
> Feel free to test the change by editing the template file! Otherwise, it will be included in the next release.

Hi @Daveiano, 
new user here. I had to manually revert this patch on a freshly installed v.3.4.0 or otherwise got no index.html, with the following trace:

weewx[2270] ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/weewx-wdc/index.html.tmpl failed with exception '<class 'Val
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/weewx-wdc/index.html.tmpl
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: **** Reason: could not convert string to float: 'geocode=45.434072'
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 348, in generate
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_weewx_wdc_index_html_tmpl_1704409132_5401943_64216.py", line 
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclu
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_weewx_wdc_includes_body_alternative_inc.py", line 286, in respond
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclu
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_weewx_wdc_includes_forecast_inc.py", line 256, in respond
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclu
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_weewx_wdc_includes_forecast_table_inc_1704409796_6408846_6211
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_weewx_wdc_includes_forecast_table_inc_1704409796_6408846_6211
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****    File "<string>", line 1, in <module>
Jan 05 00:09:56 raspberrypi python3[2270]: weewx[2270] ERROR weewx.cheetahgenerator: ****  ValueError: could not convert string to float: 'geocode=45.434072'

**Comment by Daveiano** [comment]
Hi @dave9997, the error was also noticed when the last version was released, see here: https://github.com/Daveiano/weewx-wdc/discussions/218#discussioncomment-7470782

Here is a quick fix that should help to solve the issue - these changes will be included in the next release: https://github.com/Daveiano/weewx-wdc/commit/884be1aeb0236cfee8cbadc0692eb7b93ef75d6e

Background: Every forecast provider provides the data in another format.
