### ISSUE TITLE
Can't install the latest version [BUG]

### ISSUE THREAD

**Issue by gand07** [Daveiano/weewx-wdc#209]
Hi
I try to install the latest version from yesterday. See screenshot with the error.

What have I missed?
![wdc](https://github.com/Daveiano/weewx-wdc/assets/47734099/1272954e-6857-41c9-b9c3-cc0a726ee45e)

Rgds
Gert

**Comment by Daveiano** [comment]
Hi Gert,

you missed that (from the [readme](https://github.com/Daveiano/weewx-wdc#installation)):

> **Please note:** For installation, please use the generated zip archive from a release, eg. https://github.com/Daveiano/weewx-wdc/releases/download/v3.3.0/weewx-wdc-v3.3.0.zip.
Don't download the repository directly and don't use the GitHub generated zip and tar.gz archives that come alongside the release. Always use the zip archive named **weewx-wdc-vX.X.X.zip**

> Background: The files in the src/ directory are the source files (TypeScript, SCSS). When creating a release, these source files get transformed and optimized, and the output location of these transformed files is the location which matches the location in the install.py script. The weewx-wdc-vX.X.X.zip should contain all these transformed files (like service-worker.js or main.css), but if you download the current state of the repo, these files are not included and this will throw multiple `FileNotFoundError` errors while installing. For manual building of these files, see [Development](https://github.com/Daveiano/weewx-wdc/wiki/Development#build-files-short-version).

I assume you want to test the fix for GH-194? If so, you can just install the latest version 3.3.0 and replace dist/main.js with the attached [file](https://github.com/Daveiano/weewx-wdc/files/13083347/main.zip) - please de-compress first, I can not upload js files directly here.

I hope one of the solutions will work for you!

**Comment by gand07** [comment]
Thanks for the prompt answer. I'll try that.
Gert
