### ISSUE TITLE
wee_reports : wee_reports: command not found

### ISSUE THREAD

**Issue by wifi75** [Daveiano/weewx-wdc#251]
Hello after update to weewx 5.0.1 command wee_reports not working.

why?

**Comment by c0by85** [comment]
WeeWX V5 uses different commands than V4. Please read the docs. Or contact the WeeWX Google Group.

https://weewx.com/docs/5.0/utilities/weectl-about/?h=weectl
https://groups.google.com/g/weewx-user/
https://groups.google.com/g/weewx-user/c/QyXQfbXAXGs/m/oVO_kbtKAwAJ

`weectl report run` is the desired command... Run it as the WeeWX user, or u got other problems. Also a "new" change in v5. If you run it as root, no more reports are generated because the permissions are lost. You can also find everything in the google group.

Nothing to do with the weewx-wdc skin. 😉 

But here is the wrong place for WeeWX V5 support. Sorry. 🙃🤷‍♂️🤘

**Comment by Daveiano** [comment]
@c0by85 Thanks for pointing that out, you are absolutely right!

@wifi75 Please refer to the weewx docs for general support on how to run reports in weewx v5: https://weewx.com/docs/5.0/utilities/weectl-report/#run-reports-on-demand

I will update the install and upgrade instructions from the readme soon to the new v5 commands!
