### ISSUE TITLE
[BUG] Display Error Gauges Feature Text (DE)

### ISSUE THREAD

**Issue by barci335** [Daveiano/weewx-wdc#271]
**Describe the bug**
Gauges Feature - can't display ß 

**Expected behavior**
&#223 should be translated to ß

**Screenshots**
![gauge](https://github.com/Daveiano/weewx-wdc/assets/32842368/5194e6f5-0bee-4747-9cf4-879cb48d5ff1)

![workaround](https://github.com/Daveiano/weewx-wdc/assets/32842368/011bc045-fd96-4b6a-ba0a-edcdd7d46509)

**Comment by aryiu** [comment]
I think this is related to #263, the letter "é"  not showing correctly (`&#233;`).

**Comment by Daveiano** [comment]
@barci335 Fixed in [253deec](https://github.com/Daveiano/weewx-wdc/commit/253deec4582c5724f9d44eb95d0eeac7f5e1dde4). 

I attached an updated file which should solve the problem. Feel free to test it out - please rename first to main.js and then copy it to `dist/main.js` - more info on where to copy here: https://github.com/Daveiano/weewx-wdc/wiki/Development#testing-changes--updated-files

@aryiu Yes, that's the same issue. I will have a look at #263 when I am on #262!

[main.txt](https://github.com/Daveiano/weewx-wdc/files/15136012/main.txt)

**Comment by barci335** [comment]
@Daveiano Thanks!

Just tested:
![image](https://github.com/Daveiano/weewx-wdc/assets/32842368/f85dc8fe-e396-464c-916b-8125bc223a43)
works, but looks kinda weird.

**Comment by Daveiano** [comment]
Yeah, the ß looks kinda weird here. The used font is `IBM Plex Mono` - while this may look better the `IBM Plex Sans` font looks much more "natural" here:

![Screenshot from 2024-05-05 17-28-46](https://github.com/Daveiano/weewx-wdc/assets/3184897/fb8abb3a-3a76-40bf-8deb-190057ef61f8)

If you have some skills in CSS you could change this easy via this snippet:

```
.bx--tile.diagram-tile.gauge svg text.gauge-label {
  font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif
}
```
