### ISSUE TITLE
Max Min on Wind Direction / General windDir, windGustDir handling

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#39]
I see no need for max and min values for direction.
Can this be removed in the default install config?
If not, how can I remove the display of  it?

**Comment by Daveiano** [comment]
You are right, these values do not make any sense.

There is currently no way to disable them. I will remove these values in the next release.

**Comment by gary-hammer** [comment]
Thank you

**Comment by Daveiano** [comment]
Sorry, but this one is not yet resolved.

Actually, there are two places where this needs to be addressed: the classic and the alternative layout:

Alternative:
![39-alternative](https://user-images.githubusercontent.com/3184897/182401976-0269f42f-a7eb-452b-b7a2-6cc61dc345fd.png)

Classic:
![39-classic](https://user-images.githubusercontent.com/3184897/182401954-0aba8e78-5fd6-4e75-a54c-c06054d3add4.png)

I would argue to show the average instead of min/max for the alternative layout (it looks odd if there are no values at all at the bottom of the tile). 

For the classic layout, it's a bit more complicated. If we just hide the min and max column for the wind direction, it also looks odd? Perhaps we should just keep the values in the classic layout!? 

Suggestions and ideas are welcome!

**Comment by gary-hammer** [comment]
I will stay with min and max have no meaning with direction.

It may or may not appear unbalanced, but that is the purpose of a wind
rose.

**Comment by Daveiano** [comment]
@gary-hammer What do you think of combining windSpeed / windDir in one tile and windGust / windGustDir into one tile like this:

![39-wind-proposal](https://user-images.githubusercontent.com/3184897/182971621-728b671c-9c7b-41dd-8c28-cd185f37d8a5.png)

The direction is never "standalone", it always has a wind speed at the same time and vice versa. So I think this would be a good way to solve this problem and clean the skin up at the same time.

**Comment by gary-hammer** [comment]
I really like this idea!
It solves the problem and make the skin better at the same time.

**Comment by Daveiano** [comment]
Great! I will work a bit on the typography/visuals before releasing this. It should be available in an upcoming 2.1.0.

**Comment by gary-hammer** [comment]
Looking forward to it.
