### ISSUE TITLE
Odd Graphs, But Quite Artistic

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#41]
The graphs are creating very odd plots.
See a few examples attached.

![example-2](https://user-images.githubusercontent.com/12861605/182165404-aa4d8182-f79c-4c5c-80f4-8890217c025e.png)
![example-1](https://user-images.githubusercontent.com/12861605/182165406-87bf5589-8cda-4969-9021-64bcf3180cfd.png)

**Comment by Daveiano** [comment]
This usually happens because there are holes in your data. Like in your screenshots, it looks like there is a gap in the data between 21:00 and 05:00.

What you could try is to change the `curve` of these charts. For example, for changing the outTemp/dewPoint chart, you need to update `[[[[tempdew]]]]` under `[DisplayOptions][[diagrams]][[[combined_observations]]]`:

```
[[[[tempdew]]]]
    label = 'Temperature / Dewpoint'
    [[[[[obs]]]]]
        [[[[[[temp]]]]]]
                observation = "outTemp"
                curve = "linear"
        [[[[[[dew]]]]]]
                observation = "dewpoint"
               curve = "linear"
```

The default curve for these is `natural`, which seems to produce these glitches.

Possible values are: 
- basis
- cardinal
- catmullRom
- linear
- monotoneX
- monotoneY
- natural
- step
- stepAfter
- stepBefore

You could try with `linear` or `basis` if this solves the problem. Please let me know if this helps, in that case, I would add a note on this in the readme.

**Comment by gary-hammer** [comment]
I tried the 2 values suggested and see no difference.
But, as it is missing large amounts of data, let's wait until I can run continuously for 24 hours.
This is on my test/staging server and weewx is ran manually.

**Comment by Daveiano** [comment]
Ok please report back but continuous data should solve this!

I will have a look at why these changes don't make any difference (they should).

**Comment by gary-hammer** [comment]
I have enabled daemon mode and running it for 24 hours so all the data is
present.

**Comment by Daveiano** [comment]
Ok, and the plots are now ok or still quite artistic? ;)

My example from https://github.com/Daveiano/weewx-wdc/issues/41#issuecomment-1201739707 was incorrect. If you want to change the curve on said tempdew diagram, do the following:

```
[[[[tempdew]]]]
    label = 'Temperature / Dewpoint'
    curve = "linear"
    [[[[[obs]]]]]
        [[[[[[temp]]]]]]
                observation = "outTemp"
        [[[[[[dew]]]]]]
                observation = "dewpoint"
```
