### ISSUE TITLE
Show time when the min / max was reached

### ISSUE THREAD

**Issue by Supergamerx3000** [Daveiano/weewx-wdc#53]
I would find it very cool if I could still see when, for example, the maximum temperature was reached. This could be realised, for example, by a mini popup if you tap or hover on the min / max value

Excuse me if I'm too annoying 😉

![image](https://user-images.githubusercontent.com/61492037/183701429-da74b587-546a-4216-ac54-ed55555c861d.jpeg)

Kind regards
Pascal

**Comment by Daveiano** [comment]
Oh no you are not annoying, I am always happy about good feedback!

The min/max date is **only shown on the year and statistics pages** (you can hover over the label to see the tooltip with the date). This was most likely a personal decision of my own here: I am more interested in the date/time when extremes happen for a whole year or for the whole time of recording, rather than for the day or the week.

I think if this would be added then it should be configurable for all pages. So you can have the current behaviour, or enable it for additional pages like this issue suggests.

**Comment by Daveiano** [comment]
Will be included in 2.3.0.
